//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Attachment> Tbl_Attachment { get; set; }
        public virtual DbSet<Tbl_AttachmentCategory> Tbl_AttachmentCategory { get; set; }
        public virtual DbSet<Tbl_Car> Tbl_Car { get; set; }
        public virtual DbSet<Tbl_CarType> Tbl_CarType { get; set; }
        public virtual DbSet<Tbl_ClientContract> Tbl_ClientContract { get; set; }
        public virtual DbSet<Tbl_ClientInformation> Tbl_ClientInformation { get; set; }
        public virtual DbSet<Tbl_Driver> Tbl_Driver { get; set; }
        public virtual DbSet<Tbl_Fuel> Tbl_Fuel { get; set; }
        public virtual DbSet<Tbl_InsuranceType> Tbl_InsuranceType { get; set; }
        public virtual DbSet<Tbl_Logger> Tbl_Logger { get; set; }
        public virtual DbSet<Tbl_Maintenance> Tbl_Maintenance { get; set; }
        public virtual DbSet<Tbl_MaintenanceType> Tbl_MaintenanceType { get; set; }
        public virtual DbSet<Tbl_ModeOfPayment> Tbl_ModeOfPayment { get; set; }
        public virtual DbSet<Tbl_Purchase_Fuel> Tbl_Purchase_Fuel { get; set; }
        public virtual DbSet<Tbl_Purchase_Insurance> Tbl_Purchase_Insurance { get; set; }
        public virtual DbSet<Tbl_Purchase_SparePart> Tbl_Purchase_SparePart { get; set; }
        public virtual DbSet<Tbl_Purchase_Tyre> Tbl_Purchase_Tyre { get; set; }
        public virtual DbSet<Tbl_Template> Tbl_Template { get; set; }
        public virtual DbSet<Tbl_Trip> Tbl_Trip { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UserLogin> Tbl_UserLogin { get; set; }
        public virtual DbSet<Tbl_UserRoles> Tbl_UserRoles { get; set; }
        public virtual DbSet<Tbl_FuelTotal> Tbl_FuelTotal { get; set; }
        public virtual DbSet<Tbl_PettyCash_Add> Tbl_PettyCash_Add { get; set; }
        public virtual DbSet<Tbl_PettyCash_Total> Tbl_PettyCash_Total { get; set; }
        public virtual DbSet<Tbl_PettyCash_Withdrawl> Tbl_PettyCash_Withdrawl { get; set; }
        public virtual DbSet<Tbl_TyreTotal> Tbl_TyreTotal { get; set; }
        public virtual DbSet<Tbl_DomainCompany> Tbl_DomainCompany { get; set; }
        public virtual DbSet<Tbl_TripOutsource> Tbl_TripOutsource { get; set; }
        public virtual DbSet<Tbl_CreditStatus> Tbl_CreditStatus { get; set; }
        public virtual DbSet<Tbl_Vendor> Tbl_Vendor { get; set; }
    }
}
