//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Purchase_Fuel
    {
        public int Id { get; set; }
        public Nullable<int> MOPId { get; set; }
        public string InvoiceNumber { get; set; }
        public string Vat { get; set; }
        public string Amount { get; set; }
        public string Gross { get; set; }
        public string GallonsPurchased { get; set; }
        public Nullable<System.DateTime> DateofPurchase { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> DomainCompanyId { get; set; }
        public Nullable<int> CreditStatusId { get; set; }
        public Nullable<int> VendorId { get; set; }
    }
}
