//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Logger
    {
        public int Id { get; set; }
        public string ApplicationName { get; set; }
        public string AppPath { get; set; }
        public string Details { get; set; }
        public string Status { get; set; }
        public string ErrorDetails { get; set; }
        public string ErrorLevel { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
