//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Car
    {
        public int Id { get; set; }
        public string PlateNumber { get; set; }
        public string ChasisNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string PortTags { get; set; }
        public Nullable<bool> RoadPermission { get; set; }
        public Nullable<bool> LoadingPermission { get; set; }
        public string CarTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> DomainCompanyId { get; set; }
    }
}
