//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string BasicSalary { get; set; }
        public string LicenseNumner { get; set; }
        public string EmiratesId { get; set; }
        public string VisaNumber { get; set; }
        public string PassportNumber { get; set; }
        public string MedicalNumber { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public Nullable<System.DateTime> EmiratesIdExpiry { get; set; }
        public Nullable<System.DateTime> VisaExpiry { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public Nullable<System.DateTime> MedicalExpiry { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> DomainCompanyId { get; set; }
    }
}
