//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Maintenance
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Cost { get; set; }
        public Nullable<int> NumberofHours { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int CarId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public int MaintenanceCategoryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> NumberofTyres { get; set; }
        public Nullable<int> TotalTyreId { get; set; }
        public Nullable<int> DomainCompanyId { get; set; }
    }
}
